#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"

typedef enum {
    FILL_DESTROY,
    FILL_HOLLOW,
    FILL_KEEP,
    FILL_OUTLINE,
    FILL_REPLACE
} FillMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
fill_unsafe(int from_x, int from_y, int from_z,
            int to_x, int to_y, int to_z,
            McfString block_name, FillMode mode)
{
    int ret;
    int slot_id;

    slot_id = _McfString_GetSlotId(block_name);
    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case FILL_DESTROY:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%7].value\n"
                "inline execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) destroy"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z), "r"(slot_id)
            );
            return ret;
        case FILL_HOLLOW:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%7].value\n"
                "inline execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) hollow"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z), "r"(slot_id)
            );
            return ret;
        case FILL_KEEP:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%7].value\n"
                "inline execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) keep"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z), "r"(slot_id)
            );
            return ret;
        case FILL_OUTLINE:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%7].value\n"
                "inline execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block) outline"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z), "r"(slot_id)
            );
            return ret;
        case FILL_REPLACE:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%7].value\n"
                "inline execute store result score %0 vm_regs run fill %1 %2 %3 %4 %5 %6 $(block)"
                : "=r"(ret)
                : "r"(from_x), "r"(from_y), "r"(from_z),
                  "r"(to_x), "r"(to_y), "r"(to_z), "r"(slot_id)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
fill(Vec3i from, Vec3i to, Block block, FillMode mode)
{
    McfString block_name;

    block_name = Block_EnsureMcfName(block);
    if (block_name == NULL) {
        return -1;
    }
    return fill_unsafe(from.x, from.y, from.z, to.x, to.y, to.z, block_name, mode);
}

#ifdef __cplusplus
}
#endif
