#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
kill_unsafe(McfString target_name)
{
    int ret;
    int slot_id;

    slot_id = _McfString_GetSlotId(target_name);
    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline execute store result score %0 vm_regs run kill $(target)"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
kill(Target target)
{
    McfString target_name;

    target_name = _Command_RequireTargetMcf(target);
    if (target_name == NULL) {
        return -1;
    }
    return kill_unsafe(target_name);
}

#ifdef __cplusplus
}
#endif
