#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
say_unsafe(McfString text)
{
    int ret;
    int slot_id;

    slot_id = _McfString_GetSlotId(text);
    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.text set from storage std:vm mcstr.slots[%1].value\n"
        "inline execute store result score %0 vm_regs run say $(text)"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
say(String text)
{
    McfString text_mcf;

    text_mcf = _Command_RequireStringMcf(text);
    if (text_mcf == NULL) {
        return -1;
    }
    return say_unsafe(text_mcf);
}

#ifdef __cplusplus
}
#endif
