#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_say:\n"
"    inline $execute store result score r0 vm_regs run say $(text)\n"
"    ret\n"
);

static inline int
say_unsafe(int slot_id)
{
    int ret;

    if (slot_id < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{text: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.text set from storage std:vm mcstr.slots[%1].value\n"
        "inline function _ll_shared:z/libmc_cmd_say with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(slot_id)
    );
    return ret;
}

static inline int
say(String text)
{
    McfString text_mcf;
    int slot_id;

    text_mcf = _Command_RequireStringMcf(text);
    slot_id = _McfString_GetSlotId(text_mcf);
    if (slot_id < 0) {
        return -1;
    }
    return say_unsafe(slot_id);
}

#ifdef __cplusplus
}
#endif
