#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"

typedef enum {
    DESTROY,
    KEEP,
    REPLACE
} SetBlockMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
setblock_unsafe(int x, int y, int z, int slot_id, SetBlockMode mode)
{
    int ret;

    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case DESTROY:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) destroy"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case KEEP:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) keep"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        case REPLACE:
            __asm volatile (
                "inline $data modify storage std:vm ls0.block set from storage std:vm mcstr.slots[%0].value"
                :
                : "r"(slot_id)
            );
            __asm volatile (
                "$$direct_args\n"
                "inline $execute store result score %0 vm_regs run setblock %1 %2 %3 $(block)"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
setblock(Vec3i pos, Block block, SetBlockMode mode)
{
    McfString block_name;
    int slot_id;

    block_name = Block_EnsureMcfName(block);
    slot_id = _McfString_GetSlotId(block_name);
    if (slot_id < 0) {
        return -1;
    }
    return setblock_unsafe(pos.x, pos.y, pos.z, slot_id, mode);
}

#ifdef __cplusplus
}
#endif
