#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"

typedef enum {
    DESTROY,
    KEEP,
    REPLACE
} SetBlockMode;

#ifdef __cplusplus
extern "C" {
#endif

static inline int
setblock_unsafe(int x, int y, int z, McfString block_name, SetBlockMode mode)
{
    int ret;
    int slot_id;

    slot_id = _McfString_GetSlotId(block_name);
    if (slot_id < 0) {
        return -1;
    }

    switch (mode) {
        case DESTROY:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%4].value\n"
                "inline execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) destroy"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z), "r"(slot_id)
            );
            return ret;
        case KEEP:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%4].value\n"
                "inline execute store result score %0 vm_regs run setblock %1 %2 %3 $(block) keep"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z), "r"(slot_id)
            );
            return ret;
        case REPLACE:
            __asm volatile (
                "inline data modify storage std:vm s0.block set from storage std:vm mcstr.slots[%4].value\n"
                "inline execute store result score %0 vm_regs run setblock %1 %2 %3 $(block)"
                : "=r"(ret)
                : "r"(x), "r"(y), "r"(z), "r"(slot_id)
            );
            return ret;
        default:
            return -1;
    }
}

static inline int
setblock(Vec3i pos, Block block, SetBlockMode mode)
{
    McfString block_name;

    block_name = Block_EnsureMcfName(block);
    if (block_name == NULL) {
        return -1;
    }
    return setblock_unsafe(pos.x, pos.y, pos.z, block_name, mode);
}

#ifdef __cplusplus
}
#endif
