#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
summon_unsafe(McfString entity_type_name, McfString x, McfString y, McfString z)
{
    int ret;
    int entity_type_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    entity_type_slot = _McfString_GetSlotId(entity_type_name);
    x_slot = _McfString_GetSlotId(x);
    y_slot = _McfString_GetSlotId(y);
    z_slot = _McfString_GetSlotId(z);
    if (entity_type_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.entity_type set from storage std:vm mcstr.slots[%1].value\n"
        "inline data modify storage std:vm s0.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline data modify storage std:vm s0.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline data modify storage std:vm s0.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline execute store result score %0 vm_regs run summon $(entity_type) $(x) $(y) $(z)"
        : "=r"(ret)
        : "r"(entity_type_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
summon(EntityType type, Vec3d pos)
{
    int ret;
    McfString entity_type_name;
    McfString x;
    McfString y;
    McfString z;

    entity_type_name = EntityType_EnsureMcfName(type);
    if (entity_type_name == NULL) {
        return -1;
    }

    x = _Command_FormatDouble(pos.x);
    y = _Command_FormatDouble(pos.y);
    z = _Command_FormatDouble(pos.z);
    if (x == NULL || y == NULL || z == NULL) {
        McfString_Release(x);
        McfString_Release(y);
        McfString_Release(z);
        return -1;
    }

    ret = summon_unsafe(entity_type_name, x, y, z);
    McfString_Release(x);
    McfString_Release(y);
    McfString_Release(z);
    return ret;
}

#ifdef __cplusplus
}
#endif
