#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

static inline int
tp_unsafe(McfString target_name, McfString x, McfString y, McfString z)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_slot = _McfString_GetSlotId(target_name);
    x_slot = _McfString_GetSlotId(x);
    y_slot = _McfString_GetSlotId(y);
    z_slot = _McfString_GetSlotId(z);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline data modify storage std:vm s0.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline data modify storage std:vm s0.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline data modify storage std:vm s0.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline execute store result score %0 vm_regs run tp $(target) $(x) $(y) $(z)"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
tp_rot_unsafe(McfString target_name, McfString x, McfString y, McfString z,
              McfString yaw, McfString pitch)
{
    int ret;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_slot = _McfString_GetSlotId(target_name);
    x_slot = _McfString_GetSlotId(x);
    y_slot = _McfString_GetSlotId(y);
    z_slot = _McfString_GetSlotId(z);
    yaw_slot = _McfString_GetSlotId(yaw);
    pitch_slot = _McfString_GetSlotId(pitch);
    if (target_slot < 0 || x_slot < 0 || y_slot < 0 ||
        z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline data modify storage std:vm s0.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline data modify storage std:vm s0.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline data modify storage std:vm s0.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline data modify storage std:vm s0.yaw set from storage std:vm mcstr.slots[%5].value\n"
        "inline data modify storage std:vm s0.pitch set from storage std:vm mcstr.slots[%6].value\n"
        "inline execute store result score %0 vm_regs run tp $(target) $(x) $(y) $(z) $(yaw) $(pitch)"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(yaw_slot), "r"(pitch_slot)
    );
    return ret;
}

static inline int
tp_entity_unsafe(McfString target_name, McfString destination_name)
{
    int ret;
    int target_slot;
    int destination_slot;

    target_slot = _McfString_GetSlotId(target_name);
    destination_slot = _McfString_GetSlotId(destination_name);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s0.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline data modify storage std:vm s0.destination set from storage std:vm mcstr.slots[%2].value\n"
        "inline execute store result score %0 vm_regs run tp $(target) $(destination)"
        : "=r"(ret)
        : "r"(target_slot), "r"(destination_slot)
    );
    return ret;
}

static inline int
tp(Target target, Vec3d pos)
{
    int ret;
    McfString target_name;
    McfString x;
    McfString y;
    McfString z;

    target_name = _Command_RequireTargetMcf(target);
    if (target_name == NULL) {
        return -1;
    }

    x = _Command_FormatDouble(pos.x);
    y = _Command_FormatDouble(pos.y);
    z = _Command_FormatDouble(pos.z);
    if (x == NULL || y == NULL || z == NULL) {
        McfString_Release(x);
        McfString_Release(y);
        McfString_Release(z);
        return -1;
    }

    ret = tp_unsafe(target_name, x, y, z);
    McfString_Release(x);
    McfString_Release(y);
    McfString_Release(z);
    return ret;
}

static inline int
tp_rot(Target target, Vec3d pos, Vec2f rot)
{
    int ret;
    McfString target_name;
    McfString x;
    McfString y;
    McfString z;
    McfString yaw;
    McfString pitch;

    target_name = _Command_RequireTargetMcf(target);
    if (target_name == NULL) {
        return -1;
    }

    x = _Command_FormatDouble(pos.x);
    y = _Command_FormatDouble(pos.y);
    z = _Command_FormatDouble(pos.z);
    yaw = _Command_FormatFloat(rot.x);
    pitch = _Command_FormatFloat(rot.y);
    if (x == NULL || y == NULL || z == NULL || yaw == NULL || pitch == NULL) {
        McfString_Release(x);
        McfString_Release(y);
        McfString_Release(z);
        McfString_Release(yaw);
        McfString_Release(pitch);
        return -1;
    }

    ret = tp_rot_unsafe(target_name, x, y, z, yaw, pitch);
    McfString_Release(x);
    McfString_Release(y);
    McfString_Release(z);
    McfString_Release(yaw);
    McfString_Release(pitch);
    return ret;
}

static inline int
tp_entity(Target target, Target destination)
{
    McfString target_name;
    McfString destination_name;

    target_name = _Command_RequireTargetMcf(target);
    destination_name = _Command_RequireTargetMcf(destination);
    if (target_name == NULL || destination_name == NULL) {
        return -1;
    }
    return tp_entity_unsafe(target_name, destination_name);
}

#ifdef __cplusplus
}
#endif
