#pragma once

/* Generated by tools/commands/generator/generate.py. */

#include "bindings/CommandSupport.h"


#ifdef __cplusplus
extern "C" {
#endif

__asm__(
"export _ll_shared:z/libmc_cmd_tp:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tp_rot:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(x) $(y) $(z) $(yaw) $(pitch)\n"
"    ret\n"
"\n"
"export _ll_shared:z/libmc_cmd_tp_entity:\n"
"    inline $execute store result score r0 vm_regs run tp $(target) $(destination)\n"
"    ret\n"
);

static inline int
tp_unsafe(int target_slot, int x_slot, int y_slot, int z_slot)
{
    int ret;

    if (target_slot < 0 || x_slot < 0 || y_slot < 0 || z_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", x: \"\", y: \"\", z: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot)
    );
    return ret;
}

static inline int
tp_rot_unsafe(int target_slot, int x_slot, int y_slot, int z_slot,
              int yaw_slot, int pitch_slot)
{
    int ret;

    if (target_slot < 0 || x_slot < 0 || y_slot < 0 ||
        z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", x: \"\", y: \"\", z: \"\", yaw: \"\", pitch: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.x set from storage std:vm mcstr.slots[%2].value\n"
        "inline $data modify storage std:vm s6.cmd.y set from storage std:vm mcstr.slots[%3].value\n"
        "inline $data modify storage std:vm s6.cmd.z set from storage std:vm mcstr.slots[%4].value\n"
        "inline $data modify storage std:vm s6.cmd.yaw set from storage std:vm mcstr.slots[%5].value\n"
        "inline $data modify storage std:vm s6.cmd.pitch set from storage std:vm mcstr.slots[%6].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp_rot with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(x_slot), "r"(y_slot), "r"(z_slot), "r"(yaw_slot), "r"(pitch_slot)
    );
    return ret;
}

static inline int
tp_entity_unsafe(int target_slot, int destination_slot)
{
    int ret;

    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }

    __asm volatile (
        "inline data modify storage std:vm s6.cmd set value %{target: \"\", destination: \"\"%}\n"
        "inline $data modify storage std:vm s6.cmd.target set from storage std:vm mcstr.slots[%1].value\n"
        "inline $data modify storage std:vm s6.cmd.destination set from storage std:vm mcstr.slots[%2].value\n"
        "inline function _ll_shared:z/libmc_cmd_tp_entity with storage std:vm s6.cmd\n"
        "inline scoreboard players operation %0 vm_regs = r0 vm_regs"
        : "=r"(ret)
        : "r"(target_slot), "r"(destination_slot)
    );
    return ret;
}

static inline int
tp(Target target, Vec3d pos)
{
    int ret;
    McfString target_name;
    McfString x;
    McfString y;
    McfString z;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;

    target_name = _Command_RequireTargetMcf(target);
    target_slot = _McfString_GetSlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDouble(pos.x);
    x_slot = _McfString_GetSlotId(x);
    y = _Command_FormatDouble(pos.y);
    y_slot = _McfString_GetSlotId(y);
    z = _Command_FormatDouble(pos.z);
    z_slot = _McfString_GetSlotId(z);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0) {
        McfString_Release(x);
        McfString_Release(y);
        McfString_Release(z);
        return -1;
    }

    ret = tp_unsafe(target_slot, x_slot, y_slot, z_slot);
    McfString_Release(x);
    McfString_Release(y);
    McfString_Release(z);
    return ret;
}

static inline int
tp_rot(Target target, Vec3d pos, Vec2f rot)
{
    int ret;
    McfString target_name;
    McfString x;
    McfString y;
    McfString z;
    McfString yaw;
    McfString pitch;
    int target_slot;
    int x_slot;
    int y_slot;
    int z_slot;
    int yaw_slot;
    int pitch_slot;

    target_name = _Command_RequireTargetMcf(target);
    target_slot = _McfString_GetSlotId(target_name);
    if (target_slot < 0) {
        return -1;
    }

    x = _Command_FormatDouble(pos.x);
    x_slot = _McfString_GetSlotId(x);
    y = _Command_FormatDouble(pos.y);
    y_slot = _McfString_GetSlotId(y);
    z = _Command_FormatDouble(pos.z);
    z_slot = _McfString_GetSlotId(z);
    yaw = _Command_FormatFloat(rot.x);
    yaw_slot = _McfString_GetSlotId(yaw);
    pitch = _Command_FormatFloat(rot.y);
    pitch_slot = _McfString_GetSlotId(pitch);
    if (x_slot < 0 || y_slot < 0 || z_slot < 0 || yaw_slot < 0 || pitch_slot < 0) {
        McfString_Release(x);
        McfString_Release(y);
        McfString_Release(z);
        McfString_Release(yaw);
        McfString_Release(pitch);
        return -1;
    }

    ret = tp_rot_unsafe(target_slot, x_slot, y_slot, z_slot, yaw_slot, pitch_slot);
    McfString_Release(x);
    McfString_Release(y);
    McfString_Release(z);
    McfString_Release(yaw);
    McfString_Release(pitch);
    return ret;
}

static inline int
tp_entity(Target target, Target destination)
{
    McfString target_name;
    McfString destination_name;
    int target_slot;
    int destination_slot;

    target_name = _Command_RequireTargetMcf(target);
    target_slot = _McfString_GetSlotId(target_name);
    destination_name = _Command_RequireTargetMcf(destination);
    destination_slot = _McfString_GetSlotId(destination_name);
    if (target_slot < 0 || destination_slot < 0) {
        return -1;
    }
    return tp_entity_unsafe(target_slot, destination_slot);
}

#ifdef __cplusplus
}
#endif
